export const ApiErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MODEL_ALIAS_NOT_FOUND: 'MODEL_ALIAS_NOT_FOUND',
  MODEL_NOT_ALLOWED: 'MODEL_NOT_ALLOWED',
  PROVIDER_UNSUPPORTED: 'PROVIDER_UNSUPPORTED',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  RATE_LIMITED: 'RATE_LIMITED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  STREAMING_NOT_SUPPORTED: 'STREAMING_NOT_SUPPORTED',
  GATEWAY_KEY_NOT_CONFIGURED: 'GATEWAY_KEY_NOT_CONFIGURED',
  GATEWAY_KEY_MISSING: 'GATEWAY_KEY_MISSING',
  GATEWAY_KEY_INVALID: 'GATEWAY_KEY_INVALID',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  TOOLS_NOT_SUPPORTED: 'TOOLS_NOT_SUPPORTED',
  THINKING_NOT_SUPPORTED: 'THINKING_NOT_SUPPORTED',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export const DEFAULT_HTTP_STATUS_TO_CODE: Record<number, ApiErrorCode> = {
  400: ApiErrorCode.VALIDATION_FAILED,
  401: ApiErrorCode.PROVIDER_AUTH_FAILED,
  403: ApiErrorCode.GATEWAY_KEY_INVALID,
  404: ApiErrorCode.MODEL_ALIAS_NOT_FOUND,
  413: ApiErrorCode.VALIDATION_FAILED,
  429: ApiErrorCode.RATE_LIMITED,
  500: ApiErrorCode.INTERNAL_SERVER_ERROR,
  502: ApiErrorCode.PROVIDER_UNAVAILABLE,
  503: ApiErrorCode.PROVIDER_UNAVAILABLE,
  504: ApiErrorCode.PROVIDER_TIMEOUT,
};
