// ========================================
// CORE BRAND TYPE UTILITIES
// ========================================

/**
 * Core brand type utility
 * @template K - Base primitive type
 * @template T - Brand identifier
 */

export type Brand<K, T> = K & { readonly __brand: T };

/**
 * Utility to extract base type from branded type
 */

export type UnBrand<T> = T extends Brand<infer K, unknown> ? K : T;

/**
 * Generic cast function (runtime no-op, compile-time type assertion)
 */

export const brand = <B>(value: UnBrand<B>): B => value as B;

/**
 * Generic unbrand function
 */

export const unbrand = <B>(value: B): UnBrand<B> => value as UnBrand<B>;

// ========================================
// IDENTIFIERS & TRACKING (Faza 2)
// ========================================

/**
 * Request ID for correlation (format: req_<uuid> or custom)
 */
export type RequestId = Brand<string, 'RequestId'>;

/**
 * Conversation ID for grouping requests (format: conv_<uuid>)
 * Must match /^conv_[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
 */
export type ConversationId = Brand<string, 'ConversationId'>;

/**
 * Response ID generated by gateway (prefix: gw_)
 */
export type ResponseId = Brand<string, 'ResponseId'>;

/**
 * Message ID from provider (e.g., Anthropic msg_*)
 */
export type MessageId = Brand<string, 'MessageId'>;

/**
 * Tool call identifier (e.g., call_abc123)
 */
export type ToolCallId = Brand<string, 'ToolCallId'>;

/**
 * Client instance identifier from configuration
 */
export type ClientId = Brand<string, 'ClientId'>;

/**
 * Provider instance identifier (key in YAML providers section)
 */
export type ProviderInstanceId = Brand<string, 'ProviderInstanceId'>;

/**
 * JSON Schema name for structured output
 */
export type JsonSchemaName = Brand<string, 'JsonSchemaName'>;

// ========================================
// SECURITY-CRITICAL TYPES (Faza 1)
// ========================================

/**
 * Gateway client authorization key (from allowlist)
 * DO NOT confuse with ProviderApiKey!
 */
export type GatewayKey = Brand<string, 'GatewayKey'>;

/**
 * Provider API key for SDK calls (e.g., ANTHROPIC_API_KEY)
 * DO NOT confuse with GatewayKey!
 */
export type ProviderApiKey = Brand<string, 'ProviderApiKey'>;

/**
 * Environment variable reference (e.g., "ANTHROPIC_PRIMARY_API_KEY")
 */
export type EnvRef = Brand<string, 'EnvRef'>;

// ========================================
// MODEL ROUTING (Faza 2)
// ========================================

/**
 * Model alias from gateway configuration (e.g., "claude-sonnet-4-5", "gemini-flash")
 * NOT to be confused with vendor modelId!
 */
export type ModelAlias = Brand<string, 'ModelAlias'>;

/**
 * Vendor-specific model identifier (e.g., "claude-sonnet-4-5-20250929")
 * NOT to be confused with ModelAlias!
 */
export type ModelId = Brand<string, 'ModelId'>;

// ========================================
// METRICS & USAGE (Faza 3)
// ========================================

/**
 * Number of input tokens
 */
export type InputTokens = Brand<number, 'InputTokens'>;

/**
 * Number of output tokens
 */
export type OutputTokens = Brand<number, 'OutputTokens'>;

/**
 * Thinking budget in tokens (min 1024)
 */
export type ThinkingBudgetTokens = Brand<number, 'ThinkingBudgetTokens'>;

/**
 * Cost in USD
 */
export type CostUsd = Brand<number, 'CostUsd'>;

/**
 * Prompt cache hit tokens (Anthropic)
 */
export type PromptCacheHitTokens = Brand<number, 'PromptCacheHitTokens'>;

/**
 * Prompt cache creation tokens (Anthropic)
 */
export type PromptCacheCreationTokens = Brand<
  number,
  'PromptCacheCreationTokens'
>;

// ========================================
// CONFIGURATION & POLICY (Faza 4)
// ========================================

/**
 * Timeout in milliseconds (min 1)
 */
export type TimeoutMs = Brand<number, 'TimeoutMs'>;

/**
 * Rate limit: requests per second (min 1, integer)
 */
export type RateLimitRps = Brand<number, 'RateLimitRps'>;

/**
 * Rate limit: burst size (min 1, integer)
 */
export type RateLimitBurst = Brand<number, 'RateLimitBurst'>;

/**
 * Max concurrent streams (min 1, integer)
 */
export type MaxConcurrentStreams = Brand<number, 'MaxConcurrentStreams'>;

/**
 * Max retry attempts (1-5, integer)
 */
export type MaxAttempts = Brand<number, 'MaxAttempts'>;

/**
 * Current attempt number (1-based)
 */
export type AttemptNumber = Brand<number, 'AttemptNumber'>;

/**
 * Base URL for provider (validated HTTP/HTTPS)
 */
export type BaseUrl = Brand<string, 'BaseUrl'>;

/**
 * Cache key for Redis
 */
export type CacheKey = Brand<string, 'CacheKey'>;

/**
 * Cache TTL in seconds (min 0)
 */
export type CacheTtlSeconds = Brand<number, 'CacheTtlSeconds'>;

/**
 * HTTP/TCP port number (1-65535)
 */
export type Port = Brand<number, 'Port'>;

/**
 * Schema version (integer, min 1)
 */
export type SchemaVersion = Brand<number, 'SchemaVersion'>;

/**
 * OpenAI system fingerprint (pass-through)
 */
export type SystemFingerprint = Brand<string, 'SystemFingerprint'>;

// ========================================
// CONFIGURATION & POLICY — HELPERS (Faza 4)
// ========================================

export const asTimeoutMs = (value: number): TimeoutMs => {
  if (value < 1) {
    throw new Error('TimeoutMs must be >= 1');
  }
  return value as TimeoutMs;
};

export const asMaxAttempts = (value: number): MaxAttempts => {
  if (value < 1 || value > 5) {
    throw new Error('MaxAttempts must be between 1 and 5');
  }
  return Math.floor(value) as MaxAttempts;
};

export const asBaseUrl = (value: string): BaseUrl => {
  if (!value.startsWith('http://') && !value.startsWith('https://')) {
    throw new Error('BaseUrl must start with http:// or https://');
  }
  return value as BaseUrl;
};

export const asPort = (value: number): Port => {
  if (value < 1 || value > 65535) {
    throw new Error('Port must be 1-65535');
  }
  return Math.floor(value) as Port;
};

export const asCacheTtlSeconds = (value: number): CacheTtlSeconds => {
  if (value < 0) throw new Error('CacheTtlSeconds must be >=0');
  return value as CacheTtlSeconds;
};

export const asCacheKey = (value: string): CacheKey => {
  return value as CacheKey;
};

export const asSystemFingerprint = (value: string): SystemFingerprint => {
  return value as SystemFingerprint;
};

export const asRateLimitRps = (value: number): RateLimitRps => {
  if (value < 1) throw new Error('RateLimitRps must be >=1');
  return Math.floor(value) as RateLimitRps;
};

export const asRateLimitBurst = (value: number): RateLimitBurst => {
  if (value < 1) throw new Error('RateLimitBurst must be >=1');
  return Math.floor(value) as RateLimitBurst;
};

export const asMaxConcurrentStreams = (value: number): MaxConcurrentStreams => {
  if (value < 1) throw new Error('MaxConcurrentStreams must be >=1');
  return Math.floor(value) as MaxConcurrentStreams;
};

export const asAttemptNumber = (value: number): AttemptNumber => {
  if (value < 1) throw new Error('AttemptNumber must be >=1');
  return Math.floor(value) as AttemptNumber;
};

export const asSchemaVersion = (value: number): SchemaVersion => {
  if (value < 1) throw new Error('SchemaVersion must be >= 1');
  return Math.floor(value) as SchemaVersion;
};

// ========================================
// ERROR & WARNING CODES (Faza 5)
// ========================================

export type WarningCode = Brand<string, 'WarningCode'>;

// ========================================
// ERROR & WARNING CODES — HELPERS (Faza 5)
// ========================================

export const asWarningCode = (value: string): WarningCode => {
  return value as WarningCode;
};

// ========================================
// HELPERS (Fazy 1–3)
// ========================================

export const asRequestId = (value: string): RequestId => value as RequestId;
export const asConversationId = (value: string): ConversationId =>
  value as ConversationId;
export const asResponseId = (value: string): ResponseId => value as ResponseId;
export const asMessageId = (value: string): MessageId => value as MessageId;
export const asGatewayKey = (value: string): GatewayKey => value as GatewayKey;
export const asToolCallId = (value: string): ToolCallId => value as ToolCallId;
export const asClientId = (value: string): ClientId => value as ClientId;
export const asProviderInstanceId = (value: string): ProviderInstanceId =>
  value as ProviderInstanceId;
export const asJsonSchemaName = (value: string): JsonSchemaName =>
  value as JsonSchemaName;
export const asProviderApiKey = (value: string): ProviderApiKey =>
  value as ProviderApiKey;
export const asEnvRef = (value: string): EnvRef => value as EnvRef;
export const asModelAlias = (value: string): ModelAlias => value as ModelAlias;
export const asModelId = (value: string): ModelId => value as ModelId;
export const asInputTokens = (value: number): InputTokens =>
  value as InputTokens;
export const asOutputTokens = (value: number): OutputTokens =>
  value as OutputTokens;
export const asThinkingBudgetTokens = (value: number): ThinkingBudgetTokens =>
  value as ThinkingBudgetTokens;
export const asCostUsd = (value: number): CostUsd => value as CostUsd;
export const asPromptCacheHitTokens = (value: number): PromptCacheHitTokens =>
  value as PromptCacheHitTokens;
export const asPromptCacheCreationTokens = (
  value: number,
): PromptCacheCreationTokens => value as PromptCacheCreationTokens;
