import { ApiProperty } from '@nestjs/swagger';

export class ChatOutputTextDto {
  @ApiProperty({ enum: ['text'], example: 'text' })
  type: 'text';

  @ApiProperty({
    description: 'Response text generated by the model.',
    example: 'Model response text....',
  })
  text: string;
}
